# include:
#   project: "gitops/autodevops/auto-devops"
#   ref: master
#   file: Auto-DevOps.gitlab-ci.yml

variables:
  IS_DOCKER: "false"

stages:
  - build

build:
  image: golang:alpine3.15
  stage: build
  script:
    - go build -o ansible-openstack
  tags:
    - latest-runner